# A conda environment file for babelizer examples for all languages
name: wrap-all
channels:
  - conda-forge
  - nodefaults # Speeds solving env, by limiting the number of options
dependencies:
  # From examples in https://babelizer.readthedocs.io/en/mdpiper-add-cxx-example/
  - python>=3.10
  - make
  - cmake
  - pkg-config
  - c-compiler
  - bmi-c
  - cxx-compiler
  - bmi-cxx
  - fortran-compiler
  - bmi-fortran
  # - babelizer  # installs latest release. pip install below for dev
  - bmi-tester
  # - pymt>=1.3  # Not installing for now, until it gets updated

  # other dependancies to improve build workflow
  - gimli.units=0.3.1 # Before reorg (https://github.com/mcflugen/gimli/pull/18) 
                      # to prevent import error with pymt=1.3.1

  # package management
  - conda
  - conda-libmamba-solver
  # PIP install requirements only if it is not  possible with conda
  - pip
  - pip:
    # - -e git+https://github.com/csdms/babelizer.git@develop  # installs head of branch
    # install head of `mdpiper/add-cxx-example` branch:
    - git+https://github.com/csdms/babelizer.git#111ed1b0f62e0a20ba373a465914ccbb5b17adb6
