# CMake generated Testfile for 
# Source directory: /Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing
# Build directory: /Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/build/testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_irf "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/build/testing/test_irf")
set_tests_properties(test_irf PROPERTIES  _BACKTRACE_TRIPLES "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;8;add_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;13;make_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;0;")
add_test(test_print_var_names "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/build/testing/test_print_var_names")
set_tests_properties(test_print_var_names PROPERTIES  _BACKTRACE_TRIPLES "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;8;add_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;14;make_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;0;")
add_test(test_get_value "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/build/testing/test_get_value")
set_tests_properties(test_get_value PROPERTIES  _BACKTRACE_TRIPLES "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;8;add_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;15;make_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;0;")
add_test(test_set_value "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/build/testing/test_set_value")
set_tests_properties(test_set_value PROPERTIES  _BACKTRACE_TRIPLES "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;8;add_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;16;make_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;0;")
add_test(test_grid_info "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/build/testing/test_grid_info")
set_tests_properties(test_grid_info PROPERTIES  _BACKTRACE_TRIPLES "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;8;add_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;17;make_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;0;")
add_test(test_initialize_from_file "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/build/testing/test_initialize_from_file")
set_tests_properties(test_initialize_from_file PROPERTIES  _BACKTRACE_TRIPLES "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;8;add_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;18;make_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;0;")
add_test(test_reinitialize "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/build/testing/test_reinitialize")
set_tests_properties(test_reinitialize PROPERTIES  _BACKTRACE_TRIPLES "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;8;add_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;19;make_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;0;")
add_test(test_conflicting_instances "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/build/testing/test_conflicting_instances")
set_tests_properties(test_conflicting_instances PROPERTIES  _BACKTRACE_TRIPLES "/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;8;add_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;20;make_test;/Users/aaufdenkampe/Documents/Python/babelizer-examples/example-cxx/bmi-example-cxx/testing/CMakeLists.txt;0;")
